openapi: 3.1.0
info:
  title: Schemas of `flow_framework._errors` Category
  description: Schemas of `flow_framework._errors` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    FlowFrameworkAPIDisabledError:
      type: object
      properties:
        error:
          type: string
          # example: This API is disabled. To enable it, set [flow_framework.enabled] to true.
        status:
          type: integer
          format: int32
    InvalidParameterError:
      type: object
      properties:
        error:
          type: string
          # example: Only the parameters [param1, param2] are permitted unless the provision parameter is set to true.
        status:
          type: integer
          format: int32
    ConflictError:
      type: object
      properties:
        error:
          type: string
          # example: You cannot use both the 'provision_workflow' and 'update_workflow_fields' parameters in the same request.
        status:
          type: integer
          format: int32
    MissingParameterError:
      type: object
      properties:
        error:
          type: string
          # example: You cannot use the 'reprovision_workflow' parameter to create a new template.
        status:
          type: integer
          format: int32
    ParameterConflictError:
      type: object
      properties:
        error:
          type: string
          # example: You cannot use the 'reprovision_workflow' and 'use_case' parameters in the same request.
        status:
          type: integer
          format: int32
    WorkFlowIdNullError:
      type: object
      properties:
        error:
          type: string
          # example: Workflow ID can not be null
        status:
          type: integer
          format: int32
    DuplicateKeyError:
      type: object
      properties:
        error:
          type: string
          description: Error message when a duplicate key is found in the request.
        status:
          type: integer
          format: int32
          description: HTTP status code for the error.
          # example: 400
    InvalidRequestBodyFieldError:
      type: object
      properties:
        error:
          type: string
          description: Error message when a request body field is not a string.
        status:
          type: integer
          format: int32
          description: HTTP status code for the error.
    RequestBodyParsingFailedError:
      type: object
      properties:
        error:
          type: string
          description: Error message when request body parsing fails.
        status:
          type: integer
          format: int32
          description: HTTP status code for the error.
          # example: 400
    WorkflowSaveError:
      type: object
      properties:
        error:
          type: string
          # example: Failed to save workflow state
        status:
          type: integer
          format: int32
    MaxWorkflowsLimitError:
      type: object
      properties:
        error:
          type: string
          # example: Maximum workflows limit reached 50
        code:
          type: integer
          format: int32
    TemplateNameRequiredError:
      type: object
      properties:
        error:
          type: string
          description: Error message when the template name is missing.
    TemplateNotFoundError:
      type: object
      properties:
        error:
          type: string
          # example: Failed to retrieve template (12345) from global context.
        code:
          type: integer
          format: int32
    InvalidTemplateVersionError:
      type: object
      properties:
        error:
          type: string
          description: Error message when the template version is invalid or missing.
          # example: Unable to parse field [version] in a version object.
    UnsupportedFieldUpdateError:
      type: object
      properties:
        error:
          type: string
          description: Error message when trying to update an unsupported field in a template.
          # example: You can not update the field [fieldName] without updating the whole template.
    WorkflowParsingError:
      type: object
      properties:
        error:
          type: string
          description: Error message when workflow parsing fails.
          # example: Unable to parse field [workflow] in a template object.
    WorkflowStepsRetrieveError:
      type: object
      properties:
        error:
          type: string
          # example: Failed to retrieve workflow step json.
        code:
          type: integer
          format: int32
    DeprovisioningError:
      type: object
      properties:
        error:
          type: string
          description: Describes the deprovisioning error and identifies resources that were not deprovisioned
          # example: Failed to deprovision some resources [connector_id Lw7PX4wBfVtHp98y06wV].
      required:
        - error
    DeprovisioningForbiddenError:
      type: object
      properties:
        error:
          type: string
          description: Describes the resources that require the `allow_delete` parameter for deprovisioning
          # example: These resources require the `allow_delete` parameter to deprovision [index_name my-index].
      required:
        - error
    RequestTimeoutError:
      type: object
      properties:
        error:
          type: string
          description: Error message when the request times out.
        status:
          type: integer
          format: int32
          description: HTTP status code for the error.
          # example: 408
    BadRequestError:
      type: object
      properties:
        error:
          type: string
          description: Error message when the request body or parameters are invalid.
          # example: Invalid request body or query parameters.
        status:
          type: integer
          format: int32
          description: HTTP status code for the error.
          # example: 400