openapi: 3.1.0
info:
  title: Schemas of `replication._common` Category.
  description: Schemas of `replication._common` category..
  version: 1.0.0
paths: {}
components:
  schemas:
    Replication:
      type: object
      properties:
        leader_alias:
          $ref: '_common.yaml#/components/schemas/IndexAlias'
        leader_index:
          $ref: '_common.yaml#/components/schemas/IndexName'
        use_roles:
          $ref: '#/components/schemas/UseRoles'
    UseRoles:
      type: object
      properties:
        leader_cluster_role:
          type: string
        follower_cluster_role:
          type: string
    Status:
      type: object
      properties:
        status:
          type: string
          enum:
            - BOOTSTRAPPING
            - PAUSED
            - REPLICATION NOT IN PROGRESS
            - RUNNING
            - SYNCING
        reason:
          type: string
        leader_alias:
          $ref: '_common.yaml#/components/schemas/IndexAlias'
        leader_index:
          $ref: '_common.yaml#/components/schemas/IndexName'
        follower_index:
          $ref: '_common.yaml#/components/schemas/IndexName'
        syncing_details:
          $ref: '#/components/schemas/SyncingDetails'
    SyncingDetails:
      type: object
      properties:
        leader_checkpoint:
          type: integer
          format: int32
        follower_checkpoint:
          type: integer
          format: int32
        seq_no:
          $ref: '_common.yaml#/components/schemas/SequenceNumber'
    LeaderStatus:
      type: object
      properties:
        num_replicated_indices:
          type: number
          format: double
        operations_read:
          type: number
          format: double
        translog_size_bytes:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        operations_read_lucene:
          type: number
          format: double
        operations_read_translog:
          type: number
          format: double
        total_read_time_lucene_millis:
          $ref: '_common.yaml#/components/schemas/StringifiedEpochTimeUnitMillis'
        total_read_time_translog_millis:
          $ref: '_common.yaml#/components/schemas/StringifiedEpochTimeUnitMillis'
        bytes_read:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        index_stats:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/IndexStatus'
    IndexStatus:
      type: object
      properties:
        operations_read:
          type: number
          format: double
        translog_size_bytes:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        operations_read_lucene:
          type: number
          format: double
        operations_read_translog:
          type: number
          format: double
        total_read_time_lucene_millis:
          $ref: '_common.yaml#/components/schemas/StringifiedEpochTimeUnitMillis'
        total_read_time_translog_millis:
          $ref: '_common.yaml#/components/schemas/StringifiedEpochTimeUnitMillis'
        bytes_read:
          $ref: '_common.yaml#/components/schemas/ByteCount'
    FollowerStatus:
      type: object
      properties:
        num_syncing_indices:
          type: number
          format: double
        num_bootstrapping_indices:
          type: number
          format: double
        num_paused_indices:
          type: number
          format: double
        num_failed_indices:
          type: number
          format: double
        num_shard_tasks:
          type: number
          format: double
        num_index_tasks:
          type: number
          format: double
        operations_written:
          type: number
          format: double
        operations_read:
          type: number
          format: double
        failed_read_requests:
          type: number
          format: double
        throttled_read_requests:
          type: number
          format: double
        failed_write_requests:
          type: number
          format: double
        throttled_write_requests:
          type: number
          format: double
        follower_checkpoint:
          type: number
          format: double
        leader_checkpoint:
          type: number
          format: double
        total_write_time_millis:
          $ref: '_common.yaml#/components/schemas/StringifiedEpochTimeUnitMillis'
        index_stats:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/IndexFollowerStatus'
    IndexFollowerStatus:
      type: object
      properties:
        operations_written:
          type: number
          format: double
        operations_read:
          type: number
          format: double
        failed_read_requests:
          type: number
          format: double
        throttled_read_requests:
          type: number
          format: double
        failed_write_requests:
          type: number
          format: double
        throttled_write_requests:
          type: number
          format: double
        follower_checkpoint:
          type: number
          format: double
        leader_checkpoint:
          type: number
          format: double
        total_write_time_millis:
          $ref: '_common.yaml#/components/schemas/StringifiedEpochTimeUnitMillis'
    AutoFollowStatus:
      type: object
      properties:
        num_success_start_replication:
          type: number
          format: double
        num_failed_start_replication:
          type: number
          format: double
        num_failed_leader_calls:
          type: number
          format: double
        failed_indices:
          type: array
          items:
            type: string
        autofollow_stats:
          type: array
          items:
            $ref: '#/components/schemas/AutoFollowStats'
    AutoFollowStats:
      type: object
      properties:
        name:
          type: string
        pattern:
          type: string
        num_success_start_replication:
          type: number
          format: double
        num_failed_start_replication:
          type: number
          format: double
        num_failed_leader_calls:
          type: number
          format: double
        failed_indices:
          type: array
          items:
            type: string
        last_execution_time:
          type: number
          format: double
    SettingsBody:
      type: object
      properties:
        index:
          $ref: '#/components/schemas/IndexSchema'
    UpdateSettings:
      type: object
      properties:
        settings:
          allOf:
            - type: object
              properties:
                index.number_of_shards:
                  type: integer
                  format: int32
                index.number_of_replicas:
                  type: integer
                  format: int32
            - $ref: '#/components/schemas/SettingsBody'
    IndexSchema:
      type: object
      properties:
        number_of_shards:
          type: integer
          format: int32
        number_of_replicas:
          type: integer
          format: int32
    CreateReplicationRule:
      type: object
      properties:
        leader_alias:
          $ref: '_common.yaml#/components/schemas/IndexAlias'
        name:
          type: string
        pattern:
          type: string
        use_roles:
          $ref: '#/components/schemas/UseRoles'
    DeleteReplicationRule:
      type: object
      properties:
        leader_alias:
          $ref: '_common.yaml#/components/schemas/IndexAlias'
        name:
          type: string